const {Logo,Badge}=window.DesentupidoraAlertaDesignSystem_e6b749;
const ITEMS=[['Hidrojateamento de rede de esgoto (até 30 m)',1,'serv.',650],['Limpeza de caixa de gordura',2,'un.',180],['Coleta e transporte de efluente — caminhão vácuo 12m³',1,'viagem',890]];
const brl=v=>v.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
function QuoteDocument({cliente='Condomínio Exemplo',numero='2026-0412'}){const total=ITEMS.reduce((s,[,q,,v])=>s+q*v,0);
return <div style={{width:794,minHeight:1123,background:'#fff',fontFamily:'var(--font-sans)',color:'var(--text-body)',display:'flex',flexDirection:'column',boxShadow:'var(--shadow-lg)'}}>
<div style={{background:'var(--grain),var(--grad-forest)',backgroundBlendMode:'overlay,normal',padding:'36px 48px',display:'flex',justifyContent:'space-between',alignItems:'center',color:'#fff'}}><Logo height={58}/><div style={{textAlign:'right'}}><div style={{font:'800 34px var(--font-sans)',textTransform:'uppercase',letterSpacing:'-.02em'}}>Orçamento</div><div style={{fontSize:14,color:'var(--lime-400)'}}>Nº {numero} · 05/10/2026</div></div></div>
<div style={{padding:'36px 48px',display:'flex',flexDirection:'column',gap:28,flex:1}}>
<div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:24,fontSize:14}}><div><div style={{font:'600 12px var(--font-sans)',letterSpacing:'var(--ls-wide)',textTransform:'uppercase',color:'var(--teal-600)',marginBottom:6}}>Cliente</div><div style={{fontWeight:600,fontSize:16,color:'var(--ink-900)'}}>{cliente}</div><div>Fortaleza — CE</div></div><div><div style={{font:'600 12px var(--font-sans)',letterSpacing:'var(--ls-wide)',textTransform:'uppercase',color:'var(--teal-600)',marginBottom:6}}>Validade</div><div>15 dias · Visita técnica realizada</div><div style={{marginTop:8}}><Badge tone="light">Atendimento 24h</Badge></div></div></div>
<table style={{width:'100%',borderCollapse:'collapse',fontSize:14}}><thead><tr style={{background:'var(--lime-100)',color:'var(--teal-800)',textAlign:'left'}}>{['Serviço','Qtd.','Un.','Valor'].map((x,i)=><th key={x} style={{padding:'10px 12px',fontWeight:600,textAlign:i>0?'right':'left'}}>{x}</th>)}</tr></thead>
<tbody>{ITEMS.map(([d,q,u,v])=><tr key={d} style={{borderBottom:'1px solid var(--border-default)'}}><td style={{padding:'12px'}}>{d}</td><td style={{padding:12,textAlign:'right'}}>{q}</td><td style={{padding:12,textAlign:'right'}}>{u}</td><td style={{padding:12,textAlign:'right',fontWeight:600,color:'var(--ink-900)'}}>{brl(q*v)}</td></tr>)}</tbody></table>
<div style={{alignSelf:'flex-end',background:'var(--teal-700)',color:'#fff',borderRadius:'var(--radius-md)',padding:'16px 24px',display:'flex',gap:32,alignItems:'baseline'}}><span style={{fontSize:14,textTransform:'uppercase',letterSpacing:'var(--ls-wide)'}}>Total</span><span style={{font:'800 30px var(--font-sans)'}}>{brl(total)}</span></div>
<div style={{fontSize:13,lineHeight:1.5,color:'var(--text-muted)'}}><b style={{color:'var(--ink-900)'}}>Condições:</b> pagamento na conclusão do serviço. Garantia sobre os serviços prestados. Valores podem variar se a visita identificar pontos adicionais.</div></div>
<div style={{background:'var(--teal-700)',color:'#fff',padding:'18px 48px',display:'flex',justifyContent:'space-between',fontSize:13}}><span>⁸⁵ 98905.1654</span><span>Rua Dr. Humberto Rodrigues, 200 — Mondubim</span><span>@desentupidoraalerta</span></div></div>}
window.QuoteDocument=QuoteDocument;