const {Logo,WhatsAppContact,CheckList,Badge}=window.DesentupidoraAlertaDesignSystem_e6b749;
const Photo=({label,style})=><div style={{border:'3px dashed rgba(255,255,255,.45)',borderRadius:16,display:'flex',alignItems:'center',justifyContent:'center',color:'rgba(255,255,255,.7)',font:'500 28px var(--font-sans)',textAlign:'center',padding:24,...style}}>{label}</div>;
const S1080={width:1080,height:1080,position:'relative',overflow:'hidden',display:'flex',flexDirection:'column',fontFamily:'var(--font-sans)',color:'#fff'};
function PostFossa({h}){return <div style={{...S1080,background:'var(--grain),var(--grad-forest)',backgroundBlendMode:'overlay,normal',alignItems:'center',padding:'70px 60px'}}>
<Logo height={110}/><div style={{marginTop:56,font:'800 136px/0.9 var(--font-sans)',textTransform:'uppercase',letterSpacing:'-.03em',textAlign:'center'}}>{h||<>Fossa cheia<br/>não avisa.</>}</div>
<div style={{alignSelf:'stretch',display:'flex',gap:30,marginTop:50,flex:1}}><p style={{flex:1,margin:0,font:'400 38px/1.3 var(--font-sans)'}}>Coleta com caminhão vácuo de até 20m³. Rápido, rastreável e ambientalmente correto.</p><Photo label="Foto: caminhão vácuo" style={{flex:1}}/></div>
<div style={{marginTop:40,'--label-bg':'#18473A'}}><WhatsAppContact scale={2}/></div></div>}
function PostEntupimento({h}){return <div style={{...S1080,background:'var(--grain),var(--grad-teal)',backgroundBlendMode:'overlay,normal',alignItems:'center',padding:'70px 20px'}}>
<Logo height={110}/><div style={{marginTop:60,font:'800 152px/0.9 var(--font-sans)',textTransform:'uppercase',letterSpacing:'-.035em',textAlign:'center'}}>{h||<>Entupimento<br/>não volta.</>}</div>
<p style={{margin:'40px 0 0',font:'400 46px/1.35 var(--font-sans)',textAlign:'center'}}>Hidrojateamento de alta pressão.<br/>Limpeza técnica que resolve de vez.</p>
<div style={{marginTop:'auto','--label-bg':'#0D7570'}}><WhatsAppContact scale={2}/></div></div>}
function PostRalo({h}){return <div style={{...S1080,background:'var(--grain),var(--grad-teal)',backgroundBlendMode:'overlay,normal',padding:80,display:'grid',gridTemplateColumns:'1fr 1fr',gap:40}}>
<Photo label="Foto produto: ralo + sifão" style={{alignSelf:'center',height:520}}/>
<div style={{display:'flex',flexDirection:'column',gap:50}}><div style={{lineHeight:.92}}><div style={{font:'800 140px var(--font-sans)',letterSpacing:'-.04em'}}>{h||'Ralo'}</div><div style={{font:'600 64px var(--font-sans)'}}>entupido?</div><div style={{font:'500 92px/0.95 var(--font-sans)',letterSpacing:'-.03em'}}>A gente resolve <b style={{fontWeight:800}}>na hora.</b></div></div><div style={{'--label-bg':'#0F7B76'}}><WhatsAppContact scale={1.5}/></div></div>
<div style={{gridColumn:'1/3',display:'flex',justifyContent:'space-between',alignItems:'flex-end'}}><CheckList size={42} items={['Praticidade','agilidade','e garantia']}/><Logo height={120}/></div></div>}
function Post20Anos({h}){return <div style={{...S1080,background:'var(--amber-500)',padding:'110px 40px',alignItems:'center'}}>
<div style={{font:'800 170px/0.88 var(--font-sans)',textTransform:'uppercase',letterSpacing:'-.035em',textAlign:'center'}}>{h||<>20 anos<br/>resolvendo<br/>o que ninguém<br/>quer ver.</>}</div>
<p style={{margin:'40px 0 0',font:'400 52px/1.3 var(--font-sans)',textAlign:'center'}}>Alerta Gestão de Resíduos.<br/>Fortaleza e todo o Ceará.</p><div style={{marginTop:'auto'}}><Logo variant="white" height={120}/></div></div>}
function PostAviso({h}){return <div style={{...S1080,background:'var(--lime-500)',color:'var(--forest-900)'}}>
<div style={{flex:1,padding:'90px 110px',display:'flex',flexDirection:'column',gap:50}}>
<div style={{display:'flex',gap:36,alignItems:'center'}}><div style={{width:160,height:160,border:'5px solid var(--teal-700)',borderRadius:36,display:'flex',alignItems:'center',justifyContent:'center'}}><Logo variant="symbol" height={70}/></div><div style={{font:'700 60px/1.1 var(--font-sans)',color:'var(--teal-700)'}}>{h||<>Aviso feriado de<br/><span style={{background:'var(--teal-700)',color:'#fff',padding:'0 10px'}}>Nossa Senhora</span><br/><span style={{background:'var(--teal-700)',color:'#fff',padding:'0 10px'}}>da Assunção</span></>}</div></div>
<div style={{background:'var(--teal-700)',color:'#fff',borderRadius:56,padding:'56px 60px',display:'flex',gap:36,alignItems:'center'}}><div style={{width:80,height:80,borderRadius:'50%',background:'var(--lime-500)',color:'var(--teal-700)',display:'flex',alignItems:'center',justifyContent:'center',flexShrink:0}}><Ic n="arrow-right" s={48} w={3}/></div><p style={{margin:0,font:'400 34px/1.4 var(--font-sans)'}}>Devido ao feriado, <b>não funcionaremos neste sábado (15/08)</b>. <span style={{color:'var(--lime-400)'}}>Retornaremos às nossas atividades na <b>segunda-feira, dia 17/08.</b></span></p></div>
<div style={{alignSelf:'center',background:'var(--lime-100)',color:'var(--teal-700)',borderRadius:999,padding:'14px 56px',font:'500 34px var(--font-sans)'}}>Bom Feriado!</div></div>
<div style={{background:'var(--teal-700)',padding:'34px 60px',display:'flex',flexDirection:'column',alignItems:'center',gap:20,color:'#fff'}}><Logo height={80}/><div style={{display:'flex',gap:60,font:'400 26px var(--font-sans)'}}><span>⁸⁵ 98905.1654</span><span>Fortaleza e Região Metropolitana</span><span>@alertadesentupidora</span></div></div></div>}
function PostMeme({h}){return <div style={{...S1080,background:'var(--grad-leaf)',padding:'90px 80px',alignItems:'center'}}>
<div style={{alignSelf:'flex-start',font:'700 68px/1.15 var(--font-sans)',textTransform:'uppercase'}}>{h||<>“Você é bom de<br/>matemática?”</>}</div><div style={{alignSelf:'flex-start',font:'700 56px var(--font-sans)',marginTop:30}}>EU:</div>
<Photo label="Ilustração/emoji do meme" style={{width:'90%',height:240,marginTop:30}}/>
<div style={{marginTop:40,textAlign:'center',font:'600 38px/1.35 var(--font-sans)',textTransform:'uppercase',color:'var(--lime-200)'}}><span style={{color:'#fff'}}>Entupiu?</span><br/>Nosso caminhão na porta.<br/>A conta fecha rápido<br/>quando a gente chega.</div>
<div style={{marginTop:'auto',display:'flex',alignItems:'center',gap:30}}><Logo height={100}/><div style={{'--label-bg':'#14A853'}}><WhatsAppContact scale={1.2}/></div></div></div>}
window.PostTemplates={PostFossa,PostEntupimento,PostRalo,Post20Anos,PostAviso,PostMeme};